name: Create Artix Linux image

on:
  push:
    branches: [ master ]

jobs:
  base:
    runs-on: ubuntu-latest

    steps:
      - name: Download scripts
        run: |
          wget https://gitea.artixlinux.org/artix/artix-bootstrap/raw/branch/master/artix-bootstrap.sh
          wget https://gitea.artixlinux.org/artix/artix-bootstrap/raw/branch/master/artix-rootfs.sh

      - name: Modify rootfs script
        run: |
          sed -i -e "s/inits=('openrc' 'runit' 's6' 'dinit')/inits=('runit')/g; s|tar -cpzf ../artixlinux-bootstrap-\$(date +'%Y.%m.%d')-\$init-x86_64.tar.gz \*|tar -cvJpf ../artixlinux-bootstrap-\$(date +'%Y.%m.%d')-\$init-x86_64.tar.xz \*|g" artix-rootfs.sh

      - name: Grant execute permission for scripts
        run: |
          chmod +x artix-bootstrap.sh
          chmod +x artix-rootfs.sh

      - name: Run script
        run: sudo ./artix-rootfs.sh

      - name: Run ls
        run: ls

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: artix-base
          path: artixlinux-bootstrap-*-runit-x86_64.tar.xz
