name: Create Arch Linux image

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Download scripts
        run: |
        wget https://gitea.artixlinux.org/artix/artix-bootstrap/raw/branch/master/artix-bootstrap.sh
        wget https://gitea.artixlinux.org/artix/artix-bootstrap/raw/branch/master/artix-rootfs.sh

      - name: Modify script
        run: |
          sed -i "s/inits=('openrc' 'runit' 's6' 'dinit')/inits=('runit')/g" artix-rootfs.sh

      - name: Grant execute permission for scripts
        run: |
          chmod +x artix-bootstrap.sh
          chmod +x artix-rootfs.sh

      - name: Run script
        run: ./artix-rootfs.sh

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: john-ps4-linux
          path: artixlinux-bootstrap-*-runit-x86_64.tar.gz
